//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeSharp.BOL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeeSharp.BOL.Resources.AppSettings", typeof(AppSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Achivments/{0}.
        /// </summary>
        internal static string AchivmentImageDirectory {
            get {
                return ResourceManager.GetString("AchivmentImageDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komunikat.
        /// </summary>
        internal static string AlertTitle {
            get {
                return ResourceManager.GetString("AlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.3.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓.
        /// </summary>
        internal static string CheckMark {
            get {
                return ResourceManager.GetString("CheckMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///namespace HelloWorld
        ///{
        ///    public class Hello 
        ///    {
        ///        public static void Main() 
        ///        {
        ///            Console.WriteLine(&quot;Hello World!&quot;);
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert(&apos;{0}&apos;);.
        /// </summary>
        internal static string JavaScriptAlert {
            get {
                return ResourceManager.GetString("JavaScriptAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} %.
        /// </summary>
        internal static string PercentagePattern {
            get {
                return ResourceManager.GetString("PercentagePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content\Samples\{0}.txt.
        /// </summary>
        internal static string ProgramFilesDirectory {
            get {
                return ResourceManager.GetString("ProgramFilesDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejrzystość nowym ledwo Worończańskim osoby przez zwierciadlanéj. Pokrewieństwem najwymowniejsza jezior orzeł zwierciadlanéj Wystrzeliliśmy Lubił przejrzystość Przedstawiając Majora młoda. Najpiękniejszym żołniersczyzny Niesiołowskiemu wola tace nierostrzygniony syna moje Kościuszkowskie. Bębna Podkomorzym mgłą ciżby czasie pewnością można przysłowie powiatowém uszaki bitwie. Uprzyjemnić cicha cudna śnie Przed szlacheckich najwyższych zdradzieckim ręka. Zdał Kulturze Brał kawiarka czernił dziwo oboje Gdzi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RandomText {
            get {
                return ResourceManager.GetString("RandomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jesteś w sekcji: {0}.
        /// </summary>
        internal static string SectionPrefixPattern {
            get {
                return ResourceManager.GetString("SectionPrefixPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} %.
        /// </summary>
        internal static string ShowPercentage {
            get {
                return ResourceManager.GetString("ShowPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/MovieText/{0}.txt.
        /// </summary>
        internal static string TextDirectory {
            get {
                return ResourceManager.GetString("TextDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niezalogowany.
        /// </summary>
        internal static string UnloggedAlert {
            get {
                return ResourceManager.GetString("UnloggedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja: {0}.
        /// </summary>
        internal static string VersionMessagePattern {
            get {
                return ResourceManager.GetString("VersionMessagePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content\MovieCourses\{0}.mp4.
        /// </summary>
        internal static string VideoDirectory {
            get {
                return ResourceManager.GetString("VideoDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlFiles.
        /// </summary>
        internal static string XmlFileDirectory {
            get {
                return ResourceManager.GetString("XmlFileDirectory", resourceCulture);
            }
        }
    }
}
