//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeSharp.BOL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exception {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exception() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeeSharp.BOL.Resources.Exception", typeof(Exception).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod nie jest numerem!.
        /// </summary>
        internal static string CodeIsNotNumber {
            get {
                return ResourceManager.GetString("CodeIsNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawne dane do logowania!.
        /// </summary>
        internal static string IncorrectLoginCreditentials {
            get {
                return ResourceManager.GetString("IncorrectLoginCreditentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login {0} jest już używany!
        ///Proszę wpisz inny login..
        /// </summary>
        internal static string LoginIsUsed {
            get {
                return ResourceManager.GetString("LoginIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wpisano poprawnie loginu!.
        /// </summary>
        internal static string LoginNameNotFound {
            get {
                return ResourceManager.GetString("LoginNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten moduł nie jest jeszcze dostępny! Możesz przejść do modułu następnego, licząc od modułu ostatnio zakończonego. .
        /// </summary>
        internal static string ModuleNotAllowed {
            get {
                return ResourceManager.GetString("ModuleNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie zaczęto kursu! Kurs można zacząć poprzez kliknięcie na pozycję 1.1 na liście..
        /// </summary>
        internal static string TutorialNotStarted {
            get {
                return ResourceManager.GetString("TutorialNotStarted", resourceCulture);
            }
        }
    }
}
