//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeSharp.BOL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Greetings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Greetings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeeSharp.BOL.Resources.Greetings", typeof(Greetings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miłego dnia, {0}!.
        /// </summary>
        internal static string DefaultPattern {
            get {
                return ResourceManager.GetString("DefaultPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wesołego piątku, {0}!.
        /// </summary>
        internal static string FridayPattern {
            get {
                return ResourceManager.GetString("FridayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miłego poniedziałku, {0}!.
        /// </summary>
        internal static string MondayPattern {
            get {
                return ResourceManager.GetString("MondayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udanej soboty, {0}!.
        /// </summary>
        internal static string SaturdayPattern {
            get {
                return ResourceManager.GetString("SaturdayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spokojnej niedzieli, {0}!.
        /// </summary>
        internal static string SundayPattern {
            get {
                return ResourceManager.GetString("SundayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miłego czwartku, {0}!.
        /// </summary>
        internal static string ThursdayPattern {
            get {
                return ResourceManager.GetString("ThursdayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spokojnego wtorku, {0}!.
        /// </summary>
        internal static string TuesdayPattern {
            get {
                return ResourceManager.GetString("TuesdayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udanej środy, {0}!.
        /// </summary>
        internal static string WenesdayPattern {
            get {
                return ResourceManager.GetString("WenesdayPattern", resourceCulture);
            }
        }
    }
}
